### ISSUE TITLE
如何更改cell children的颜色

### ISSUE THREAD

**Issue by LGinC** [mallfoundry/taroify#202]
`style={{'--cell-value-color': '#1989fa'}}>`
没有生效

如果是通过scss或less覆盖内置样式又该如何操作？

**Comment by tgioer** [comment]
目前没有 --cell-value-color 变量，下个大版本会加上，目前可以使用嵌套 css

**Comment by LGinC** [comment]
`<Cell title='费用'><Text style={{color: 'red'}}>{this.state?.order.price}元</Text></Cell>`
好吧,就这样将就用了

**Comment by tgioer** [comment]
你可以：

```tsx
<Cell className="custom" />
```

```scss 
.custom {
  .taroify-cell__value {
  color : ...
  
  }
}
```
