### ISSUE TITLE
[Feature Request] Loading 圆圈太细了颜色浅点根本看不清

### ISSUE THREAD

**Issue by skyliwq** [mallfoundry/taroify#407]
### 使用示例，包括组件或 Hooks

圆圈太细了颜色浅点根本看不清 在哪里可以设置与圆环粗细

**Comment by tgioer** [comment]
目前没有提供 CSS Var
可以通过设置 `taroify-loading__circular` class 的 `border-width` 改变粗细：
```tsx
.taroify-loading__circular {
    border-width: 2px;
}
```

**Comment by tgioer** [comment]
https://github.com/mallfoundry/taroify/pull/409

**Comment by tgioer** [comment]
在下一个版本可以直接使用 CSS var
```css
element.style {
  --loading-circular-border-width: 2px;
}
```
