### ISSUE TITLE
[Bug Report] search组件onClear不会触发, search组件使用css vars修改搜索icon颜色无效，并且无法修改placeholder颜色

### ISSUE THREAD

**Issue by Vinsurs** [mallfoundry/taroify#529]
### 问题出在哪个包

@taroify/core

### 问题出在哪个平台/设备/浏览器

微信小程序, 百度小程序

### 平台/设备/浏览器

所有设备

### 你正在使用的 Taroify 版本是多少

0.0.23-alpha.1

### 描述一下您遇到的问题以及重现步骤

```tsx
<Search
        className={clsx(myStyles["top-search"], "top-search")}
        shape="round"
        placeholder="请输入搜索关键词"
        value={keyword}
        onChange={this.handleKeywordChange}
        onSearch={() => this.search(1)}
        clearable={true}
       onClear={this.handleSearchClear}
      />
```

- search组件设置clearable属性后，然而onClear不会触发,
实际是 点击清除图标只会触发onChange, 而不会触发onClear; 就算是自定义清除icon，情况也是如此。
- search组件使用css vars修改搜索icon颜色无效，
使用如下css样式修改search 的搜索icon的颜色，好像不起作用
```css
// global.css
.top-search {
  --search-left-icon-color: pink;
}
```
- 并且无法修改placeholder颜色
使用如下css样式修改search 的placeholder的颜色，好像不起作用, placeholder的样色始终是黑色，尤其是我设置了`--search-content-background-color: rgba(238, 238, 238, 0.12);`, 很难看，
```css
// global.css
.top-search {
  input::placeholder {
   color: red;
  }
}
```
