### ISSUE TITLE
[Feature Request] FixedNav 是否可以有触发小程序客服

### ISSUE THREAD

**Issue by WyntersN** [mallfoundry/taroify#780]
### 使用示例，包括组件或 Hooks

 FixedNav 是否可以有触发小程序客服
有例子么
![image](https://github.com/user-attachments/assets/d992ddf4-f481-4158-87c5-300b7e1450ca)

### 你想为这个功能创建一个 PR 吗

None

**Comment by Pilotager** [comment]
可以，我加下这个能力

**Comment by Pilotager** [comment]
### 自定义内容

```tsx
const CustomerFixedNav = () => {
  const [open, setOpen] = useState(false)

  return (
    <FixedNav
      open={open}
      onChange={setOpen}
      type="left"
      backdrop={false}
      position={{ top: "400px" }}
      content={
        <>
          <GiftOutlined color="#FFF" />
          <span className="fixed-nav-text">{open ? "开" : "关"}</span>
        </>
      }
    >
      <ul className="taroify-fixed-nav_content customer">
        <li className="taroify-fixed-nav_content_item">我</li>
        <li className="taroify-fixed-nav_content_item">是</li>
        <li className="taroify-fixed-nav_content_item">自</li>
        <li className="taroify-fixed-nav_content_item">定</li>
        <li className="taroify-fixed-nav_content_item">义</li>
      </ul>
    </FixedNav>
  )
}
```

```scss
.fixed-nav-demo {
  .fixed-nav-text {
    color: #fff;
    line-height: 26px;
    width: 48px;
    font-size: 24px;
  }

  .taroify-fixed-nav_content {
    &.customer {
      border-radius: 0 50px 50px 0;
      margin: 0;
      padding-left: 160px;
      padding-right: 40px;
      right: auto;
    }

    &_item {
      align-items: center;
      color: #1a1a1a;
      display: flex;
      flex: 1;
      flex-direction: column;
      flex-shrink: 0;
      height: 100%;
      justify-content: center;
      min-width: 100px;
      position: relative;
      font-size: 28px;
    }
  }
}
```
